### PR TITLE
#2 - Add authentication

### LINKED ISSUE #2: Add authentication
- User can register account
- Error message is shown if  login or register fails
- Login is successful only with valid credentials
- Verification email is send after user's account is created

### PR DESCRIPTION
**Pull request by krzysztofkozyra021**
This should close #2

### CODE REVIEW

File: database/migrations/0001_01_01_000000_create_users_table.php [hunk 1]
```diff
@@ -15,6 +16,7 @@ public function up(): void
             $table->string("email")->unique();
             $table->timestamp("email_verified_at")->nullable();
             $table->string("password");
+            $table->enum("role", array_column(Role::cases(), "value"))->default(Role::USER->value);
```
[the remark this answers is not in the document]
Comment (krzysztofkozyra021) [reply database/migrations/0001_01_01_000000_create_users_table.php:19]: So I should not delete the enum field but somehow convert it to string in new migration ? If so, how to delete Role class without error, Class Role not found in old migration?

File: app/Actions/Fortify/CreateNewUser.php [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+
+class CreateNewUser implements CreatesNewUsers
+{
+    use PasswordValidationRules;
+
+    public function create(array $input): User
+    {
+        Validator::make($input, [
+            "name" => ["required", "string", "max:255"],
+            "email" => ["required", "string", "email", "max:255", "unique:users"],
```
Comment (AleksandraKozubal) [inline app/Actions/Fortify/CreateNewUser.php:21]: Maybe use Rule::unique()?

File: database/factories/PetShelterAddressFactory.php [hunk 3]
```diff
@@ -0,0 +1,22 @@
+<?php
+
+declare(strict_types=1);
+
+namespace Database\Factories;
+
+use Illuminate\Database\Eloquent\Factories\Factory;
+
+/**
+ * @extends Factory<\App\Models\PetShelterAddress>
```
Comment (AleksandraKozubal) [inline database/factories/PetShelterAddressFactory.php:10]: here as well

**Review by AleksandraKozubal — COMMENTED** [review]
Please include this change

image

**Review by AleksandraKozubal — CHANGES_REQUESTED** [review]
I did `php artisan migrate:fresh --seed` and this happened:
image

**Review by AleksandraKozubal — COMMENTED** [review]
Check Files changed tab, there's a few github comments
image

**Review by AleksandraKozubal — COMMENTED** [review]
Now I have this on ` http://interns2025c.blumilk.local.env` :
image

**Review by AleksandraKozubal — CHANGES_REQUESTED** [review]
1. Log in button on landing page has href="#" 
2. Translations for validation errors are missing
image

3. "Potwierdź swoją e-mail" -> "Potwierdź swój email", those buttons on the right could be more styled and image could be set to the cat and dogs icon
image

4.  Will you provide translations of views content here or in another pr?

**Review by AleksandraKozubal — COMMENTED** [review]
1. Please provide validation as I described
2. 
image
error occurs on click Enable: `ReferenceError: axios is not defined`

**Review by AleksandraKozubal — COMMENTED** [review]
How can I go to the profile page? After login I still see "Log in ->" button

**Review by EwelinaSkrzypacz — DISMISSED** [review]

File: resources/js/Components/Header.vue [hunk 4]
```diff
@@ -9,8 +9,10 @@ import {
   Bars3Icon,
   XMarkIcon,
 } from '@heroicons/vue/24/outline'
+import NavLink from './NavLink.vue'
 
 const mobileMenuOpen = ref(false)
+
```
Comment (AleksandraKozubal) [inline resources/js/Components/Header.vue:15]:
```suggestion
```

File: resources/js/Layouts/AppLayout.vue [hunk 5]
```diff
@@ -0,0 +1,187 @@
...
+
+    <Banner />
+
+    <div class="min-h-screen bg-gray-100 dark:bg-gray-900">
+      <nav class="bg-white dark:bg-gray-800 border-b border-gray-100 dark:border-gray-700">
+        <!-- Primary Navigation Menu -->
+        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
+          <div class="flex justify-between h-16">
+            <div class="flex">
+              <!-- Logo -->
```
Comment (AleksandraKozubal) [inline resources/js/Layouts/AppLayout.vue:38]: Please remove all comments

**Review by kamilpiech97 — CHANGES_REQUESTED** [review]

File: tests/Feature/UpdatePasswordTest.php [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+    {
+        $this->actingAs($user = User::factory()->create());
+
+        $response = $this->put("/user/password", [
+            "current_password" => "wrong-password",
+            "password" => "new-password",
+            "password_confirmation" => "new-password",
+        ]);
+
+        $response->assertSessionHasErrors();
```
Comment (AleksandraKozubal) [inline tests/Feature/UpdatePasswordTest.php:39]: You can add what fields should throw error

**Review by kamilpiech97 — APPROVED** [review]

**Review by EwelinaSkrzypacz — APPROVED** [review]

**Review by kamilpiech97 — APPROVED** [review]
